spring.datasource.url=${POSTGRE_URL}
spring.datasource.username=${POSTGRE_USERNAME}
spring.datasource.password=${POSTGRE_PASSWORD}
spring.datasource.hikari.keepaliveTime=30000
spring.datasource.hikari.maxLifetime=600000
spring.datasource.hikari.maximum-pool-size=10