spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${ROOT_PASSWORD}
server.servlet.context-path=/api/v1.0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=${BREVO_USERNAME}
spring.mail.password=${BREVO_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=${BREVO_EMAIL}

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=3600000

finance.tracker.frontend.url = ${FINANCE_FRONTEND_URL}

app.activation.url=${FINANCE_BACKEND_URL}
spring.profiles.active=prod